# -*- coding: utf-8 -*-
"""Shakhandar_davrisheva_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bOkIhLHHl-FPUwBxOSkB3tDwJe3Rizcy

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is.

Algorithms is  a stated solution of a problem in order and  in simple way .

Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]

Brute force means that you will go through all possible solutions . For example, as we talked in lesson aboout a  chess game, , the brute force will go through all possible combination of moves, without taking anything in consideration. But when it comes to algorithmic design is method which used to create mathematical processing  to solve problems.

In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice.

Even nowadays every fıeld has an impact of algorithmic design, also architecture .In architecture even it has own term as parametric design . It is a process, which is  based on algorithmic thinking that help us to  the expression of parameters and rules that, together, define, encode and clarify the relationship between design intent and design response. Algorithmic design now goes together with architecture,the  main reason to my point of view is an identical design , mostly buildings which are designed by slgorithmic design are outstanding , they became a landmark of that country , for instance Zaha Hadids Heydar Alieyev cultural center in Baku . Now algorithmic design has affected my practice and in the future it will increase its influence on us . It forcing to change even  our education system , architecture students will start to learn coding as software engineers maybe .  In the futere as in all fields it will be not enough to have one specialization .

Create a python dictionary for your name surname and year of birth.
"""

dict = {'name': 'shakhnandar', 'surname': 'davrisheva', 'birth':'1997'}
dict ['name']

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if 'shakhandar'[0] == 'a':
   print ('my initial is a!')
else:
   print ('my initial is s!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len('davrisheva')%3:
  print ('it is divisible')
else:
  print ('not divisible')

"""Change your year of birth to 2678."""

dict = {'name': 'shakhnandar', 'surname': 'davrisheva', 'birth':'1997'}
if '1997'[0] == '2':
  print('wrong')
else :
  print('birth date is 2678' )

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""